// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_claro.Infrastructure.Persistence;

#nullable disable

namespace backend_claro.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831200242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_claro.Domain.Entities.CuentaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CuentaUsuarios");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.DetalleTrabajo", b =>
                {
                    b.Property<int>("DetalleTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleTrabajoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("DetalleTrabajoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.Property<int>("OrdenTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenTrabajoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrecioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sot")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("OrdenTrabajoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.OrdenTrabajoArchivo", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArchivoId"));

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArchivoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.DetalleTrabajo", b =>
                {
                    b.HasOne("backend_claro.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_claro.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("backend_claro.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.OrdenTrabajoArchivo", b =>
                {
                    b.HasOne("backend_claro.Domain.Entities.OrdenTrabajo", "OrdenT")
                        .WithMany("Archivos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenT");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("backend_claro.Domain.Entities.CuentaUsuario", "Cuenta")
                        .WithOne("Perfil")
                        .HasForeignKey("backend_claro.Domain.Entities.Usuario", "AuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.CuentaUsuario", b =>
                {
                    b.Navigation("Perfil")
                        .IsRequired();
                });

            modelBuilder.Entity("backend_claro.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
